# Generated by Django 5.2.6 on 2025-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_studnet_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
